import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import CodeBlock from '@theme/CodeBlock';
import { Collapsible } from '../Utils/Collapsible';

// --- Utils ---
const toKebabCase = (str: string) =>
    str
        .match(/[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g)
        ?.map((x) => x.toLowerCase())
        .join('') || '';

// --- Context ---
interface ProjectState {
    projectName: string;
    projectId: string;
    versioning: boolean;
    sidebarType: 'autogenerated' | 'manual';
}

interface ProjectContextType extends ProjectState {
    setProjectName: (name: string) => void;
    setProjectId: (id: string) => void;
    setVersioning: (v: boolean) => void;
    setSidebarType: (t: 'autogenerated' | 'manual') => void;
}

const ProjectContext = createContext<ProjectContextType | undefined>(undefined);

export const ProjectProvider = ({ children }: { children: ReactNode }) => {
    const [projectName, setProjectName] = useState('');
    const [projectId, setProjectId] = useState('');
    const [versioning, setVersioning] = useState(false);
    const [sidebarType, setSidebarType] = useState<'autogenerated' | 'manual'>('autogenerated');

    // Auto-generate ID
    useEffect(() => {
        if (!projectId || projectId === toKebabCase(projectName.slice(0, -1))) {
            setProjectId(toKebabCase(projectName));
        }
    }, [projectName]);

    return (
        <ProjectContext.Provider
            value={{
                projectName,
                projectId,
                versioning,
                sidebarType,
                setProjectName,
                setProjectId,
                setVersioning,
                setSidebarType,
            }}
        >
            {children}
        </ProjectContext.Provider>
    );
};

const useProject = () => {
    const context = useContext(ProjectContext);
    if (!context) {
        throw new Error('useProject must be used within a ProjectProvider');
    }
    return context;
};

// --- Components ---

export const ProjectInputs = () => {
    const { projectName, setProjectName, projectId, setProjectId, versioning, setVersioning, sidebarType, setSidebarType } = useProject();

    const title = (
        <div>
            <h3 style={{ margin: 0 }}>Project Configuration</h3>
            <p className="margin-bottom--none text--secondary" style={{ fontSize: '0.9em' }}>
                Enter details to customize the guide below.
            </p>
        </div>
    );

    return (
        <Collapsible title={title} defaultOpen={false} className="margin-bottom--lg">
            <div className="row">
                <div className="col col--6">
                    <div className="margin-bottom--md">
                        <label className="text--bold">Project Name</label>
                        <input
                            className="button button--outline button--secondary button--block text--left"
                            style={{ cursor: 'text' }}
                            type="text"
                            placeholder="e.g. FortiHub"
                            value={projectName}
                            onChange={(e) => setProjectName(e.target.value)}
                        />
                    </div>
                </div>
                <div className="col col--6">
                    <div className="margin-bottom--md">
                        <label className="text--bold">Project ID (Slug)</label>
                        <input
                            className="button button--outline button--secondary button--block text--left"
                            style={{ cursor: 'text' }}
                            type="text"
                            placeholder="e.g. fortihub"
                            value={projectId}
                            onChange={(e) => setProjectId(e.target.value)}
                        />
                    </div>
                </div>
            </div>
            <div className="row">
                <div className="col col--6">
                    <label className="text--bold">Sidebar Type</label>
                    <select
                        className="button button--outline button--secondary button--block text--left"
                        value={sidebarType}
                        onChange={(e) => setSidebarType(e.target.value as any)}
                    >
                        <option value="autogenerated">Autogenerated (Recommended)</option>
                        <option value="manual">Manual</option>
                    </select>
                </div>
                <div className="col col--6" style={{ display: 'flex', alignItems: 'flex-end' }}>
                    <label style={{ cursor: 'pointer', display: 'flex', alignItems: 'center', marginBottom: '10px' }}>
                        <input
                            type="checkbox"
                            checked={versioning}
                            onChange={(e) => setVersioning(e.target.checked)}
                            style={{ marginRight: '0.5rem' }}
                        />
                        Enable Versioning
                    </label>
                </div>
            </div>
        </Collapsible>
    );
};

export const DynamicText = ({ children, defaultText = '<proj-name>' }: { children?: (state: ProjectState) => string, defaultText?: string }) => {
    const state = useProject();
    if (!state.projectId && !state.projectName) return <span style={{ opacity: 0.6 }}>{defaultText}</span>;

    if (children) {
        return <span>{children(state)}</span>;
    }
    return <span>{state.projectName || state.projectId}</span>;
}

export const DynamicCode = ({ children, language = 'bash' }: { children: string | ((state: ProjectState) => string), language?: string }) => {
    const state = useProject();

    let content = '';
    if (typeof children === 'function') {
        content = children(state);
    } else {
        // Basic replacement for simple strings if needed, though function is preferred for complex logic
        content = children
            .replace(/<proj-name>/g, state.projectId || '<proj-name>')
            .replace(/<Project Name>/g, state.projectName || '<Project Name>');
    }

    return <CodeBlock language={language}>{content}</CodeBlock>;
};
